name: Send Build Status Email

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  send_notification:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send notification email
        uses: dawidd6/action-send-mail@v3
        with:
          from: altauil@gmail.com
          to: fadal@softserveinc.com
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: altauil@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Actions Build Status"
          body: "The build status is: ${{ github.event.workflow_run.conclusion }}"
